name: SonarQube Scan

on: push

jobs:

  sonar:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: SonarQube Scan

        run: |

          docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli

sqa_34546a84c93b78f4ece1e55a40e8b16857e533d7
